################################################################################
# Specify the Default settings to be used.
#
agentPool: dev
resources:
  limits:
    cpu: 2
    memory: 8
  requests:
    cpu: 0.2
elasticsearch:
  nodeCount: 3
  storagePerNodeGB: 128
