trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /pipelines/*
    exclude:
    - /**/*.md

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - /pipelines/*
    exclude:
    - /**/*.md

variables:
- group: 'iac-terraform-variables'

stages:
- template: stage-compose.yml
  parameters:
    environments:
    - name: 'devint'
  #     enablePrIsolation: true
  #     resourceNameIsolationLevel: 8
    - name: 'qa'
  #     enablePrIsolation: false
  #     resourceNameIsolationLevel: 0

    configurations:
    - jobName: template_deployment
      terraformTemplatePath: '$(TF_DEPLOYMENT_TEMPLATE_ROOT)'
      # deploymentTimeoutInMinutes: 120