parameters:
  environments: []
  configurations: []
  forceRun: false

stages:

- stage: publish_artifact
  displayName: 'Initialize'
  pool:
    vmImage: 'ubuntu-16.04'
  jobs:
  - template: publish-artifact.yml

- ${{ each environment in parameters.environments }}:
  - ${{ each config in parameters.configurations }}:

    - stage: ${{ config.jobName }}_${{ environment.name }}_build
      displayName: 'Build ${{ config.jobName }}-${{ environment.name }}'
      pool:
        vmImage: 'ubuntu-16.04'
      jobs:
      - job: TemplateChangeDetection_${{ config.jobName }}_Build
        displayName: Analyze Changes
        steps:
        - template: tasks/detect-cicd.yml
          parameters:
            terraformTemplatePath: ${{ config.terraformTemplatePath }}
            jobName: ${{ config.jobName }}
      - template: stage-build.yml
        parameters:
          environment: ${{ environment.name }}
          enablePrIsolation: ${{ environment.enablePrIsolation }}
          resourceNameIsolationLevel: ${{ environment.resourceNameIsolationLevel }}
          configuration: ${{ config }}

    - stage: ${{ config.jobName }}_${{ environment.name }}_deploy
        pool:
          vmImage: 'ubuntu-16.04'
      displayName: 'Deploy ${{ config.jobName }}-${{ environment.name }}'
      jobs:
      - job: TemplateChangeDetection_${{ config.jobName }}_Deploy
        displayName: Determine Changes
        condition: not(coalesce(variables.FORCE_RUN, ${{ parameters.forceRun }}))
        steps:
        - template: tasks/detect-cicd.yml
          parameters:
            terraformTemplatePath: ${{ config.terraformTemplatePath }}
            jobName: ${{ config.jobName }}
      - template: stage-deploy.yml
        parameters:
          environment: ${{ environment.name }}
          enablePrIsolation: ${{ environment.enablePrIsolation }}
          resourceNameIsolationLevel: ${{ environment.resourceNameIsolationLevel }}
          configuration: ${{ config }}
