{{- $list := split "," .Values.clusterNames}}
{{- $agentPool := .Values.agentPool}}
{{- $memLimit := .Values.resources.limits.memory}}
{{- $cpuReq := .Values.resources.requests.cpu}}
{{- $cpuLimit := .Values.resources.limits.cpu}}
{{- $version := .Values.elasticsearch.version}}
{{- $nodeCount := .Values.elasticsearch.nodeCount}}
{{- $nodeStorage := .Values.elasticsearch.storagePerNodeGB}}
{{- range $index, $app := $list}}
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: "elasticsearch"
spec:
  version: {{ $version }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: ClusterIP
  nodeSets:
    - name: default
      count: {{ $nodeCount }}
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ $nodeStorage }}Gi
            storageClassName: managed-premium
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      podTemplate:
        spec:
          nodeSelector:
            agentpool: {{ $agentPool }}
          tolerations:
          - key: "sku"
            operator: "Equal"
            value: "elasticsearch"
            effect: "NoSchedule"
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms{{ div $memLimit 2 }}g -Xmx{{ div $memLimit 2 }}g"
          resources:
            requests:
              cpu: {{ $cpuReq }}
            limits:
              memory: {{ $memLimit }}Gi
              cpu: {{ $cpuLimit }}
{{- end}}
