name: Generate terraform docs
on: [push, pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Network Module
      uses: terraform-docs/gh-actions@v0.11.0
      with:
        working-dir: ./modules/network
        output-file: README.md
        output-method: inject
        git-push: "true"


    # - name: Submodule
    #   uses: Dirrk/terraform-docs@v1.0.8
    #   with:
    #     tf_docs_working_dir: ./modules/network/subnet/
    #     tf_docs_output_file: README.md
    #     tf_docs_output_method: inject
    #     tf_docs_git_push: 'true'