name: Generate Terraform Documentation
on:
  workflow_dispatch:
  push:
    paths:
      - 'modules/**'
jobs:

  naming:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f modules/naming-rules/bin/requirements.txt ]; then pip install -r modules/naming-rules/bin/requirements.txt; fi
    - name: Create local changes
      run: |
        cd modules/naming-rules
        python bin/run.py
    - name: CheckIn
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Update Naming Conventions'
        add: '.'

  docs:
    runs-on: ubuntu-latest
    needs: naming
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: ResourceGroup Module
      uses: terraform-docs/gh-actions@v0.11.0
      with:
        working-dir: ./modules/resource-group
        output-file: README.md
        output-method: inject
        git-push: "true"

    - name: Network Module
      uses: terraform-docs/gh-actions@v0.11.0
      with:
        working-dir: ./modules/network
        output-file: README.md
        output-method: inject
        git-push: "true"

    - name: Subnet Module
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: ./modules/network/subnet/
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'

    - name: AKS Module
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: ./modules/aks/
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'

    - name: AD Application
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: ./modules/ad-application/
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'

    - name: Service Principal
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: ./modules/service-principal/
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'

    - name: DNS Zone
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: ./modules/dns-zone
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'

    - name: Storage Module
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: ./modules/storage-account
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'

    - name: NGINX Ingress
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: ./modules/nginx-ingress
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'

    - name: Certificate Manager
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: ./modules/cert-manager
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'