name: Generate Naming Rules
on:
  workflow_dispatch:
  push:
    paths:
      - 'modules/naming-rules/**'
jobs:

  naming-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f modules/naming-rules/bin/requirements.txt ]; then pip install -r modules/naming-rules/bin/requirements.txt; fi
    - name: Create local changes
      run: |
        cd modules/naming-rules
        python bin/run.py
    - name: CheckIn
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Update Naming Conventions'
        add: '.'